layout_spectrum: 0.20628281929899045
typography_spectrum: 0.049304798258892675
color:
  saturation: 0.46443669617415806
  brandStrength: 0.12308415275020985
  lightness: 0.24105515739991154
  brandColors:
    - '#000000'
    - '#FFFFFF'
  rhythmicContrast: 0.45879444806181857
content_rating:
  adult: false
github: true
analytics:
  google: UA-89544743-1
  facebook: '1702506510062219'
author:
  name: Muhammad Khojali
  email: mak@makarts.io
  url: 'http://makarts.io/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4673b58b-e9fc-41a1-a4f3-72839d60f2f9.png
name: MAKARTS
url: 'http://makarts.io'
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/makarts.io/'
    type: external
  - name: Behance
    url: 'https://www.behance.net/makhojali'
    type: external
  - name: LinkedIn
    url: 'https://linkedin.com/in/makhojail'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/makhojali/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b6670e87-15d4-471e-a601-d894f6ed5e38.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: MAKARTS
content: []
description: Creative Director | Musician & Visual artist
purpose:
  - type: external
    url: 'https://twitter.com/makhojali'
    label: Say Hello
  - type: contact
    url: 'mailto:business@makarts.io'
    label: Contact me
