layout_spectrum: 0.20538145480585276
typography_spectrum: 0.16223767139377201
color:
  saturation: 0.5314924818078185
  brandStrength: 0.5210270629340948
  lightness: 0.940925316749657
  brandColors:
    - '#000000'
    - '#FFFFFF'
  rhythmicContrast: 0.9151806977567365
content_rating:
  adult: false
github: true
analytics:
  google: ''
  facebook: ''
author:
  name: Muhammad Khojali
  email: mak@makarts.io
  url: 'http://makarts.io/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/49740727-9419-4c62-9e12-a3720fa8eb19.png
name: MAKARTS
url: 'http://makarts.io'
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/makarts.io/'
    type: external
  - name: Behance
    url: 'https://www.behance.net/makhojali'
    type: external
  - name: LinkedIn
    url: 'https://linkedin.com/in/makhojail'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/makhojali/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b6670e87-15d4-471e-a601-d894f6ed5e38.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: MAKARTS
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FZhvV261M_Sw%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DZhvV261M_Sw&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FZhvV261M_Sw%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: MAK
          url: 'https://www.youtube.com/user/Makartstudio'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - acoustic
        - mak
        - shaf
        - time
        - time to breathe
        - guitar (musical instrument)
        - flute (musical instrument)
        - photography (visual art form)
        - creative director (job ti...
      description: >-
        Music video by MAK performing Time to breathe . (C) 2015 Production
        House : Khalid Awad Studio https://soundcloud.com/makhojali
        https://instagram.com/makkhojali/ https://twitter.com/makhojali
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=ZhvV261M_Sw&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=ZhvV261M_Sw&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=ZhvV261M_Sw&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=ZhvV261M_Sw&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=ZhvV261M_Sw&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=ZhvV261M_Sw'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=ZhvV261M_Sw
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=ZhvV261M_Sw
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=ZhvV261M_Sw'
      title: Time to breathe - MAK feat. SHAF ( Acoustic )
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: external
    url: 'https://twitter.com/makhojali'
    label: Follow
  - type: contact
    url: 'mailto:business@makarts.io'
    label: Contact
