layout_spectrum: 0.6767058285274128
typography_spectrum: 0.49241086518825355
color:
  saturation: 0.8754145313541193
  brandStrength: 0.6238358667602597
  lightness: 0.23539343327163986
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#2F2F2F'
    - '#6F6F6F'
    - '#AFAFAF'
  rhythmicContrast: 0.9944277523791805
title: MAKARTS
content: []
github: true
purpose:
  - type: external
    url: 'https://twitter.com/makhojali'
    label: Say Hello
  - type: contact
    url: 'mailto:business@makarts.io'
    label: Business inquiries
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: ''
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b6670e87-15d4-471e-a601-d894f6ed5e38.png
author:
  name: Muhammad Khojali
  email: mak@makarts.io
  url: makarts.io
name: MAKARTS
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/712588d3-a00a-48c4-b207-a1383094b124.png
