typography_spectrum: 0.17052163248079472
color:
  saturation: 0.884184631019886
  brandStrength: 0.39154428624335935
  lightness: 0.9374083546388636
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.2759208470087794
github: true
layout_spectrum: 0.20687417716230497
analytics:
  google: UA-89544743-1
  facebook: '1702506510062219'
author:
  name: Muhammad Khojali
  email: mak@makarts.io
  url: makarts.io
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/712588d3-a00a-48c4-b207-a1383094b124.png
name: MAKARTS
url: 'http://makarts.io'
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/makarts.io/'
    type: external
  - name: Behance
    url: 'https://www.behance.net/makhojali'
    type: external
  - name: LinkedIn
    url: 'https://linkedin.com/in/makhojail'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/makhojali/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b6670e87-15d4-471e-a601-d894f6ed5e38.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: MAKARTS
content: []
description: ''
purpose:
  - type: external
    url: 'https://twitter.com/makhojali'
    label: Say Hello
  - type: contact
    url: 'mailto:business@makarts.io'
    label: Business inquiries
content_rating:
  adult: false
